openapi: 3.0.1
info:
  title: Exchange Rates APIs
  version: v 1.0
servers:
  - url: https://int.api.fiservapps.com
  - url: https://cert.api.fiservapps.com
  - url: https://prod.api.fiservapps.com
    description: Generated server url
paths:
  /fx/v1/pricing/request:
    post:
      tags:
        - Exchange Rate
      x-group-name: Exchange Rate
      x-proxy-name: Get Rate
      summary: Provides the rates information for country currency pair and scheme.
      description: This API provides the exchange rate based on merchant hierarchy setup on OpenFX 2.0 platform. It uses source currency, client cross reference ID and merchant cross reference ID and BIN to determine the exchange rate.
      operationId: rateExchange
      parameters:
        - name: Api-Key
          in: header
          description: API and Secret key will be provided as part of customer onboarding.
          required: true
          schema:
            type: string
        - name: Timestamp
          in: header
          description: Use Epoch timestamp in milliseconds in the request.
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          description: Authorization information for the request. Use API Key and Secret to build the HMAC signature Format - HMAC {hmacToken}.
          required: true
          schema:
            type: string
        - name: Client-Request-ID
          in: header
          description: A unique random number for each request.
          required: true
          schema:
            type: number
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExchangeRateRequest'
            examples:
              ExchangeRate:
                $ref: '#/components/examples/ExchangeRateRequest'
        required: true
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeRateResponse'
              examples:
                ExchangeRate:
                  $ref: '#/components/examples/ExchangeRateResponse'
        '400':
          description: The request cannot be validated
          content:
            application/json:
              schema:
                type: string
        '401':
          description: The request was unauthorized
          content:
            application/json:
              schema:
                type: string
        '404':
          description: The request resource does not exist
          content:
            application/json:
              schema:
                type: string
        '500':
          description: An unexpected internal server error occurred
          content:
            application/json:
              schema:
                type: string
        '503':
          description: The service was unavailable
          content:
            application/json:
              schema:
                type: string
        '504':
          description: The request timed out while waiting for a response
          content:
            application/json:
              schema:
                type: string
  /fx/v1/pricing/request/mcp:
    post:
      tags:
        - Exchange Rate
      x-group-name: Exchange Rate
      x-proxy-name: Get MCP Rate
      summary: Provides list of MCP exchange rates information for country currency pair and scheme.
      description: This API provides the exchange rate based on merchant hierarchy setup on OpenFX 2.0 platform. It uses source currency, client cross reference ID and merchant cross reference ID and BIN to determine the exchange rate.
      operationId: MCPRateExchange
      parameters:
        - name: Api-Key
          in: header
          description: API and Secret key will be provided as part of customer onboarding.
          required: true
          schema:
            type: string
        - name: Timestamp
          in: header
          description: Use Epoch timestamp in milliseconds in the request.
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          description: Authorization information for the request.  Use API Key and Secret to build the HMAC signature Format - HMAC {hmacToken}.
          required: true
          schema:
            type: string
        - name: Client-Request-ID
          in: header
          description: A unique random number for each request.
          required: true
          schema:
            type: number
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExchangeAllRateRequest'
            examples:
              ExchangeRate:
                $ref: '#/components/examples/ExchangeAllRateRequest'
        required: true
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeRateResponse'
              examples:
                ExchangeRate:
                  $ref: '#/components/examples/ExchangeRateResponse'
        '400':
          description: The request cannot be validated
          content:
            application/json:
              schema:
                type: string
        '401':
          description: The request was unauthorized
          content:
            application/json:
              schema:
                type: string
        '404':
          description: The request resource does not exist
          content:
            application/json:
              schema:
                type: string
        '500':
          description: An unexpected internal server error occurred
          content:
            application/json:
              schema:
                type: string
        '503':
          description: The service was unavailable
          content:
            application/json:
              schema:
                type: string
        '504':
          description: The request timed out while waiting for a response
          content:
            application/json:
              schema:
                type: string

  /fx/v1/pricing/request/allrates:
    post:
      tags:
        - Exchange Rate
      x-group-name: Exchange Rate
      x-proxy-name: Get All Rates
      summary: Provides list of exchange rates information for country currency pair and scheme.
      description: This API provides the set of exchange rate based on merchant hierarchy setup on OpenFX 2.0 platform. It uses Source currency, target currency, client cross reference ID and merchant cross reference ID to determine the exchange rate.Target currency are the optional attributes and used as filter criteria while determining the rate.
      operationId: getAllRates
      parameters:
        - name: Api-Key
          in: header
          description: API and Secret key will be provided as part of customer onboarding.
          required: true
          schema:
            type: string
        - name: Timestamp
          in: header
          description: Use Epoch timestamp in milliseconds in the request.
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          description: Authorization information for the request. Use API Key and Secret to build the HMAC signature Format - HMAC {hmacToken}.
          required: true
          schema:
            type: string
        - name: Client-Request-ID
          in: header
          description: A unique random number for each request.
          required: true
          schema:
            type: number
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExchangeAllRateRequest'
            examples:
              ExchangeAllRate:
                $ref: '#/components/examples/ExchangeAllRateRequest'
              ExchangeAllRateWithAmount:
                $ref: '#/components/examples/ExchangeAllRateRequestWithAmountRequest'
              ExchangeAllRateWithTargetCurrency:
                $ref: '#/components/examples/ExchangeAllRateRequestWithTargetCurrencyRequest'
              ExchangeAllRateRequestWithAmountAndTargetCurrency:
                $ref: '#/components/examples/ExchangeAllRateRequestWithAmountAndTargetCurrencyRequest'

        required: true
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExchangeRateResponse'
              examples:
                ExchangeAllRate:
                  $ref: '#/components/examples/ExchangeAllRateResponse'
                ExchangeAllRateWithAmount:
                  $ref: '#/components/examples/ExchangeAllRateWithAmountResponse'
                ExchangeAllRateWithTargetCurrency:
                  $ref: '#/components/examples/ExchangeAllRateWithTargetCurrencyResponse'
                ExchangeAllRateRequestWithAmountAndTargetCurrency:
                  $ref: '#/components/examples/ExchangeAllRateWithAmountAndTargetCurrencyResponse'
        '400':
          description: The request cannot be validated
          content:
            application/json:
              schema:
                type: string
        '401':
          description: The request was unauthorized
          content:
            application/json:
              schema:
                type: string
        '404':
          description: The request resource does not exist
          content:
            application/json:
              schema:
                type: string
        '500':
          description: An unexpected internal server error occurred
          content:
            application/json:
              schema:
                type: string
        '503':
          description: The service was unavailable
          content:
            application/json:
              schema:
                type: string
        '504':
          description: The request timed out while waiting for a response
          content:
            application/json:
              schema:
                type: string


  /fx/v1/pricing/bin/{currency_code}:
    get:
      tags:
        - Exchange Rate
      x-group-name: Exchange Rate
      x-proxy-name: Get BINs by Currency
      summary: Provides a list of all BINs associated for the given currency code.
      description: Request to download a list of all BINs for a specific source currency to limit the number of lookups being performed. There is an optional query parameter 'inverse' that will cause the response to be the inverse; that is, a BIN list that includes all but the specified source currency.
      operationId: getBins
      parameters:
        - name: Api-Key
          in: header
          description: API and Secret key will be provided as part of customer onboarding.
          required: true
          schema:
            type: string
        - name: Timestamp
          in: header
          description: Use Epoch timestamp in milliseconds in the request.
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          description: Authorization information for the request. Use API Key and Secret to build the HMAC signature Format - HMAC {hmacToken}.
          required: true
          schema:
            type: string
        - name: Client-Request-ID
          in: header
          description: A unique random number for each request.
          required: true
          schema:
            type: number
        - name: Currency_code
          in: path
          description: '3-character ISO-4217 alpha currency code representing the foreign currency of the rate request. Example: USD'
          required: true
          schema:
            type: string
        - name: Inverse
          in: query
          description: |-
            An optional query parameter 'inverse' that will cause
            the response to be the inverse; that is, a BIN list that is for all but the specified source currency
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BinListResponse'
              examples:
                BinList:
                  $ref: '#/components/examples/BinList'
        '400':
          description: Invalid Source Currency used
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '401':
          description: The request was unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnAuthorizedResponse'
        '404':
          description: No BIN available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundResponse'
        '500':
          description: An unexpected internal server error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorResponse'
        '503':
          description: The service was unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceUnavailableResponse'
        '504':
          description: The request timed out while waiting for a response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GatewayErrorResponse'
components:
  schemas:
    BadRequest:
      type: object
      properties:
        status:
          type: integer
          description: Status code associated with the response
          format: int32
          example: 400
        message:
          type: string
          description: Status message associated with the response
          example: The request cannot be validated
    UnAuthorizedResponse:
      type: object
      properties:
        status:
          type: integer
          description: Test Status code associated with the response
          format: int32
          example: 401
        message:
          type: string
          description: Status message associated with the response
          example: The request was unauthorized
    NotFoundResponse:
      type: object
      properties:
        status:
          type: integer
          description: Test Status code associated with the response
          format: int32
          example: 404
        message:
          type: string
          description: Status message associated with the response
          example: The requested resource does not exist
    InternalServerErrorResponse:
      type: object
      properties:
        status:
          type: integer
          description: Test Status code associated with the response
          format: int32
          example: 500
        message:
          type: string
          description: Status message associated with the response
          example: An unexpected internal server error occurred
    ServiceUnavailableResponse:
      type: object
      properties:
        status:
          type: integer
          description: Test Status code associated with the response
          format: int32
          example: 503
        message:
          type: string
          description: Status message associated with the response
          example: The service was unavailable
    GatewayErrorResponse:
      type: object
      properties:
        status:
          type: integer
          description: Test Status code associated with the response
          format: int32
          example: 504
        message:
          type: string
          description: Status message associated with the response
          example: The request timed out while waiting for a response
    DefaultResponse:
      type: object
      properties:
        status:
          type: integer
          description: Status code associated with the response
          format: int32
        message:
          type: string
          description: Status message associated with the response
          example: Some message from the service
      description: Default response
    ExchangeRateRequest:
      type: object
      properties:
        source:
          description: The 3 character ISO-4217 alpha currency code representing the base currency of the rate request.
          type: string
          enum:
            - Unknown
            - USD
            - AFN
            - DZD
            - ARS
            - AMD
            - AWG
            - AUD
            - AZN
            - BSD
            - BHD
            - THB
            - PAB
            - BBD
            - BYR
            - BZD
            - BMD
            - VEF
            - BOB
            - BRL
            - BND
            - BGN
            - BIF
            - CAD
            - CVE
            - KYD
            - XOF
            - XAF
            - XPF
            - CLP
            - COP
            - KMF
            - BAM
            - NIO
            - CRC
            - HRK
            - CUP
            - CZK
            - GMD
            - DKK
            - MKD
            - DJF
            - STD
            - DOP
            - VND
            - XCD
            - EGP
            - SVC
            - ETB
            - EUR
            - FKP
            - FJD
            - HUF
            - CDF
            - GHS
            - GIP
            - HTG
            - PYG
            - GNF
            - GWP
            - GYD
            - HKD
            - UAH
            - ISK
            - INR
            - IRR
            - IQD
            - JMD
            - JOD
            - KES
            - PGK
            - LAK
            - KWD
            - MWK
            - ZMK
            - AOA
            - MMK
            - GEL
            - LVL
            - LBP
            - ALL
            - HNL
            - SLL
            - LRD
            - LYD
            - SZL
            - LTL
            - LSL
            - MGA
            - MYR
            - MUR
            - MZN
            - MXN
            - MXV
            - MDL
            - MAD
            - BOV
            - NGN
            - ERN
            - NAD
            - NPR
            - ANG
            - ILS
            - RON
            - TWD
            - TRY
            - NZD
            - BTN
            - KPW
            - NOK
            - PEN
            - MRO
            - TOP
            - PKR
            - MOP
            - UYU
            - PHP
            - GBP
            - BWP
            - QAR
            - GTQ
            - ZAR
            - OMR
            - KHR
            - MVR
            - IDR
            - RUB
            - RWF
            - SHP
            - SAR
            - XDR
            - RSD
            - SCR
            - SGD
            - SBD
            - KGS
            - SOS
            - TJS
            - LKR
            - SDG
            - SRD
            - SEK
            - CHF
            - SYP
            - BDT
            - WST
            - TZS
            - KZT
            - TTD
            - MNT
            - TND
            - AED
            - UGX
            - COU
            - CLF
            - UYI
            - USN
            - USS
            - UZS
            - VUV
            - CHE
            - CHW
            - KRW
            - YER
            - JPY
            - CNY
            - PLN
            - XBA
            - XTS
            - XBB
            - XBD
            - XBC
            - XAU
            - XPD
            - XPT
            - XAG
            - XXX
            - XFU
            - TMT
            - ZWL
            - CUC
            - SSP
            - XUA
            - XSU
            - BYN
            - VES
            - ZMW
            - MRU
            - STN
            - SLE
            - BRC
            - ARX
        rateType:
          $ref: '#/components/schemas/RateType'
        client:
          type: string
        xref:
          type: string
        bin:
          type: string
        sourceAmount:
          type: number
          format: double
    Currency:
      type: object
      properties:
        alpha:
          type: string
        numeric:
          type: integer
          format: int32
        minorUnits:
          type: integer
          format: int32
        symbol:
          type: string
    ExchangeRate:
      type: object
      properties:
        provider:
          type: string
        rate:
          type: number
          format: double
        id:
          type: string
        start:
          type: string
        end:
          type: string
        rateType:
          $ref: '#/components/schemas/RateType'
        source:
          $ref: '#/components/schemas/Currency'
        target:
          $ref: '#/components/schemas/Currency'
    ExchangeRateResponse:
      type: object
      properties:
        eligibility:
          type: string
          enum:
            - 'Y'
            - 'N'
            - D
        id:
          type: string
        margin:
          type: number
          format: double
        sourceAmount:
          type: string
        targetAmount:
          type: string
        rate:
          $ref: '#/components/schemas/ExchangeRate'
    ExchangeAllRateRequest:
      type: object
      properties:
        source:
          type: string
          enum:
            - Unknown
            - USD
            - AFN
            - DZD
            - ARS
            - AMD
            - AWG
            - AUD
            - AZN
            - BSD
            - BHD
            - THB
            - PAB
            - BBD
            - BYR
            - BZD
            - BMD
            - VEF
            - BOB
            - BRL
            - BND
            - BGN
            - BIF
            - CAD
            - CVE
            - KYD
            - XOF
            - XAF
            - XPF
            - CLP
            - COP
            - KMF
            - BAM
            - NIO
            - CRC
            - HRK
            - CUP
            - CZK
            - GMD
            - DKK
            - MKD
            - DJF
            - STD
            - DOP
            - VND
            - XCD
            - EGP
            - SVC
            - ETB
            - EUR
            - FKP
            - FJD
            - HUF
            - CDF
            - GHS
            - GIP
            - HTG
            - PYG
            - GNF
            - GWP
            - GYD
            - HKD
            - UAH
            - ISK
            - INR
            - IRR
            - IQD
            - JMD
            - JOD
            - KES
            - PGK
            - LAK
            - KWD
            - MWK
            - ZMK
            - AOA
            - MMK
            - GEL
            - LVL
            - LBP
            - ALL
            - HNL
            - SLL
            - LRD
            - LYD
            - SZL
            - LTL
            - LSL
            - MGA
            - MYR
            - MUR
            - MZN
            - MXN
            - MXV
            - MDL
            - MAD
            - BOV
            - NGN
            - ERN
            - NAD
            - NPR
            - ANG
            - ILS
            - RON
            - TWD
            - TRY
            - NZD
            - BTN
            - KPW
            - NOK
            - PEN
            - MRO
            - TOP
            - PKR
            - MOP
            - UYU
            - PHP
            - GBP
            - BWP
            - QAR
            - GTQ
            - ZAR
            - OMR
            - KHR
            - MVR
            - IDR
            - RUB
            - RWF
            - SHP
            - SAR
            - XDR
            - RSD
            - SCR
            - SGD
            - SBD
            - KGS
            - SOS
            - TJS
            - LKR
            - SDG
            - SRD
            - SEK
            - CHF
            - SYP
            - BDT
            - WST
            - TZS
            - KZT
            - TTD
            - MNT
            - TND
            - AED
            - UGX
            - COU
            - CLF
            - UYI
            - USN
            - USS
            - UZS
            - VUV
            - CHE
            - CHW
            - KRW
            - YER
            - JPY
            - CNY
            - PLN
            - XBA
            - XTS
            - XBB
            - XBD
            - XBC
            - XAU
            - XPD
            - XPT
            - XAG
            - XXX
            - XFU
            - TMT
            - ZWL
            - CUC
            - SSP
            - XUA
            - XSU
            - BYN
            - VES
            - ZMW
            - MRU
            - STN
            - SLE
            - BRC
            - ARX
        rateType:
          $ref: '#/components/schemas/RateType'
        client:
          type: string
        xref:
          type: string
        target:
          type: string
          enum:
            - Unknown
            - USD
            - AFN
            - DZD
            - ARS
            - AMD
            - AWG
            - AUD
            - AZN
            - BSD
            - BHD
            - THB
            - PAB
            - BBD
            - BYR
            - BZD
            - BMD
            - VEF
            - BOB
            - BRL
            - BND
            - BGN
            - BIF
            - CAD
            - CVE
            - KYD
            - XOF
            - XAF
            - XPF
            - CLP
            - COP
            - KMF
            - BAM
            - NIO
            - CRC
            - HRK
            - CUP
            - CZK
            - GMD
            - DKK
            - MKD
            - DJF
            - STD
            - DOP
            - VND
            - XCD
            - EGP
            - SVC
            - ETB
            - EUR
            - FKP
            - FJD
            - HUF
            - CDF
            - GHS
            - GIP
            - HTG
            - PYG
            - GNF
            - GWP
            - GYD
            - HKD
            - UAH
            - ISK
            - INR
            - IRR
            - IQD
            - JMD
            - JOD
            - KES
            - PGK
            - LAK
            - KWD
            - MWK
            - ZMK
            - AOA
            - MMK
            - GEL
            - LVL
            - LBP
            - ALL
            - HNL
            - SLL
            - LRD
            - LYD
            - SZL
            - LTL
            - LSL
            - MGA
            - MYR
            - MUR
            - MZN
            - MXN
            - MXV
            - MDL
            - MAD
            - BOV
            - NGN
            - ERN
            - NAD
            - NPR
            - ANG
            - ILS
            - RON
            - TWD
            - TRY
            - NZD
            - BTN
            - KPW
            - NOK
            - PEN
            - MRO
            - TOP
            - PKR
            - MOP
            - UYU
            - PHP
            - GBP
            - BWP
            - QAR
            - GTQ
            - ZAR
            - OMR
            - KHR
            - MVR
            - IDR
            - RUB
            - RWF
            - SHP
            - SAR
            - XDR
            - RSD
            - SCR
            - SGD
            - SBD
            - KGS
            - SOS
            - TJS
            - LKR
            - SDG
            - SRD
            - SEK
            - CHF
            - SYP
            - BDT
            - WST
            - TZS
            - KZT
            - TTD
            - MNT
            - TND
            - AED
            - UGX
            - COU
            - CLF
            - UYI
            - USN
            - USS
            - UZS
            - VUV
            - CHE
            - CHW
            - KRW
            - YER
            - JPY
            - CNY
            - PLN
            - XBA
            - XTS
            - XBB
            - XBD
            - XBC
            - XAU
            - XPD
            - XPT
            - XAG
            - XXX
            - XFU
            - TMT
            - ZWL
            - CUC
            - SSP
            - XUA
            - XSU
            - BYN
            - VES
            - ZMW
            - MRU
            - STN
            - SLE
            - BRC
            - ARX
        sourceAmount:
          type: number
          format: double
    BinInfo:
      type: object
      properties:
        bd:
          type: string
        id:
          type: string
        in:
          type: string
        es:
          type: string
          enum:
            - Unknown
            - AL
            - AK
            - AZ
            - AR
            - CA
            - CO
            - CT
            - DE
            - DC
            - FL
            - GA
            - GU
            - HI
            - ID
            - IL
            - IN
            - IA
            - KS
            - KY
            - LA
            - ME
            - MD
            - MA
            - MI
            - MN
            - MS
            - MO
            - MT
            - NE
            - NV
            - NH
            - NJ
            - NM
            - NY
            - NC
            - ND
            - OH
            - OK
            - OR
            - PA
            - PR
            - RI
            - SC
            - SD
            - TN
            - TX
            - UT
            - VT
            - VA
            - VI
            - WA
            - WV
            - WI
            - WY
            - AB
            - BC
            - MB
            - NB
            - NL
            - NT
            - NS
            - NU
            - 'ON'
            - PE
            - QC
            - SK
            - YT
        an:
          type: string
          enum:
            - DebitOnly
            - Amex
            - Visa
            - Master
            - Discover
            - ClosedLoop
            - Unknown
            - PrivateLabel
        ct:
          type: string
          enum:
            - CreditHybrid
            - DebitPinOnlyWithEBT
            - DebitHybrid
            - USACommercialDebitNotPinCapable
            - USACommercialDebitPinCapable
            - NonUSAConsumerDebitNotPinCapable
            - NonUSACommercialDebitNotPinCapable
            - NonUSAConsumerDebitPinCapable
            - NonUSACommercialDebitPinCapable
            - DebitPinOnlyWithoutEBT
            - PrivateLabelMC
            - SignatureOnly
            - TrueCredit
            - Unknown
        it:
          type: string
          enum:
            - Credit
            - Debit
            - Unknown
            - Prepaid
        la:
          type: string
        ha:
          type: string
        sd:
          type: string
        rl:
          type: string
          enum:
            - Unknown
            - Unregulated
            - Regulated
            - RegulatedWithFraud
        rd:
          type: string
          enum:
            - Unknown
            - Reloadable
            - NonReloadable
        ic:
          type: string
          enum:
            - Unknown
            - USA
            - AFG
            - ALB
            - DZA
            - AND
            - AGO
            - ATG
            - AZE
            - ARG
            - AUS
            - AUT
            - BHS
            - BHR
            - BGD
            - ARM
            - BRB
            - BEL
            - BMU
            - BTN
            - BOL
            - BIH
            - BWA
            - BRA
            - BLZ
            - SLB
            - VGB
            - BRN
            - BGR
            - MMR
            - BLR
            - KHM
            - CMR
            - CAN
            - CPV
            - CYM
            - LKA
            - TCD
            - CHL
            - CHN
            - TWN
            - COL
            - COM
            - MYT
            - COG
            - COD
            - COK
            - CRI
            - HRV
            - CUB
            - CYP
            - CZE
            - BEN
            - DNK
            - DMA
            - DOM
            - ECU
            - SLV
            - GNQ
            - ETH
            - ERI
            - EST
            - FRO
            - FJI
            - FIN
            - FRA
            - GUF
            - PYF
            - DJI
            - GEO
            - GMB
            - PSE
            - DEU
            - GHA
            - GIB
            - GRC
            - GRD
            - GLP
            - GUM
            - GTM
            - GIN
            - GUY
            - VAT
            - HND
            - HKG
            - HUN
            - ISL
            - IND
            - IDN
            - IRQ
            - IRL
            - ISR
            - ITA
            - CIV
            - JAM
            - JPN
            - KAZ
            - JOR
            - KEN
            - KOR
            - KWT
            - KGZ
            - LAO
            - LBN
            - LSO
            - LVA
            - LBR
            - LIE
            - LTU
            - LUX
            - MAC
            - MDG
            - MWI
            - MYS
            - MDV
            - MLT
            - MTQ
            - MRT
            - MUS
            - MEX
            - MCO
            - MNG
            - MDA
            - MNE
            - MSR
            - MAR
            - MOZ
            - OMN
            - NAM
            - NPL
            - NLD
            - CUW
            - ABW
            - SXM
            - BES
            - NCL
            - VUT
            - NZL
            - NIC
            - NGA
            - NOR
            - PLW
            - PAK
            - PAN
            - PNG
            - PRY
            - PER
            - PHL
            - POL
            - PRT
            - PRI
            - QAT
            - REU
            - ROU
            - RUS
            - RWA
            - KNA
            - AIA
            - LCA
            - VCT
            - SMR
            - SAU
            - SEN
            - SRB
            - SYC
            - SLE
            - SGP
            - SVK
            - VNM
            - SVN
            - SOM
            - ZAF
            - ZWE
            - ESP
            - SUR
            - SWZ
            - SWE
            - CHE
            - TJK
            - THA
            - TGO
            - TTO
            - ARE
            - TUN
            - TUR
            - TCA
            - UGA
            - UKR
            - MKD
            - EGY
            - GBR
            - GGY
            - JEY
            - IMN
            - TZA
            - VIR
            - BFA
            - ASM
            - BDI
            - CAF
            - SGS
            - GAB
            - KIR
            - GRL
            - HTI
            - LBY
            - MLI
            - NRU
            - ANT
            - NER
            - MNP
            - UMI
            - FSM
            - GNB
            - TLS
            - BLM
            - STP
            - SSD
            - TON
            - TKM
            - URY
            - UZB
            - VEN
            - WSM
            - YEM
            - ZMB
            - ATA
            - BVT
            - CXR
            - CCK
            - FLK
            - ALA
            - ATF
            - HMD
            - IRN
            - PRK
            - NIU
            - NFK
            - MHL
            - PCN
            - SHN
            - MAF
            - SPM
            - SDN
            - ESH
            - SJM
            - SYR
            - TKL
            - TUV
            - WLF
            - IOT
            - ROM
            - ZAR
            - TMP
            - QZZ
        ac:
          type: boolean
        d_st:
          type: string
          enum:
            - NA
            - PinPinlessPOS
            - PinPOSPinlessBillPay
            - PinPOS
            - PinPOSPinlessPOSPinlessBillPay
            - PinlessBillPay
            - PinlessPOS
            - PinlessBillPayPinlessPOS
        d_ac:
          type: string
          enum:
            - NA
            - PinPinlessPOS
            - PinPOSPinlessBillPay
            - PinPOS
            - PinPOSPinlessPOSPinlessBillPay
            - PinlessBillPay
            - PinlessPOS
            - PinlessBillPayPinlessPOS
        d_ny:
          type: string
          enum:
            - NA
            - PinPinlessPOS
            - PinPOSPinlessBillPay
            - PinPOS
            - PinPOSPinlessPOSPinlessBillPay
            - PinlessBillPay
            - PinlessPOS
            - PinlessBillPayPinlessPOS
        d_je:
          type: string
          enum:
            - NA
            - PinPinlessPOS
            - PinPOSPinlessBillPay
            - PinPOS
            - PinPOSPinlessPOSPinlessBillPay
            - PinlessBillPay
            - PinlessPOS
            - PinlessBillPayPinlessPOS
        d_in:
          type: string
          enum:
            - NA
            - PinPinlessPOS
            - PinPOSPinlessBillPay
            - PinPOS
            - PinPOSPinlessPOSPinlessBillPay
            - PinlessBillPay
            - PinlessPOS
            - PinlessBillPayPinlessPOS
        d_vi:
          type: string
          enum:
            - NA
            - PinPinlessPOS
            - PinPOSPinlessBillPay
            - PinPOS
            - PinPOSPinlessPOSPinlessBillPay
            - PinlessBillPay
            - PinlessPOS
            - PinlessBillPayPinlessPOS
        d_ma:
          type: string
          enum:
            - NA
            - PinPinlessPOS
            - PinPOSPinlessBillPay
            - PinPOS
            - PinPOSPinlessPOSPinlessBillPay
            - PinlessBillPay
            - PinlessPOS
            - PinlessBillPayPinlessPOS
        d_cu:
          type: string
          enum:
            - NA
            - PinPinlessPOS
            - PinPOSPinlessBillPay
            - PinPOS
            - PinPOSPinlessPOSPinlessBillPay
            - PinlessBillPay
            - PinlessPOS
            - PinlessBillPayPinlessPOS
        d_af:
          type: string
          enum:
            - NA
            - PinPinlessPOS
            - PinPOSPinlessBillPay
            - PinPOS
            - PinPOSPinlessPOSPinlessBillPay
            - PinlessBillPay
            - PinlessPOS
            - PinlessBillPayPinlessPOS
        d_sh:
          type: string
          enum:
            - NA
            - PinPinlessPOS
            - PinPOSPinlessBillPay
            - PinPOS
            - PinPOSPinlessPOSPinlessBillPay
            - PinlessBillPay
            - PinlessPOS
            - PinlessBillPayPinlessPOS
        d_eb:
          type: string
          enum:
            - NA
            - PinPinlessPOS
            - PinPOSPinlessBillPay
            - PinPOS
            - PinPOSPinlessPOSPinlessBillPay
            - PinlessBillPay
            - PinlessPOS
            - PinlessBillPayPinlessPOS
        d_it:
          type: string
          enum:
            - NA
            - PinPinlessPOS
            - PinPOSPinlessBillPay
            - PinPOS
            - PinPOSPinlessPOSPinlessBillPay
            - PinlessBillPay
            - PinlessPOS
            - PinlessBillPayPinlessPOS
        d_pu:
          type: string
          enum:
            - NA
            - PinPinlessPOS
            - PinPOSPinlessBillPay
            - PinPOS
            - PinPOSPinlessPOSPinlessBillPay
            - PinlessBillPay
            - PinlessPOS
            - PinlessBillPayPinlessPOS
        d_at:
          type: string
          enum:
            - NA
            - PinPinlessPOS
            - PinPOSPinlessBillPay
            - PinPOS
            - PinPOSPinlessPOSPinlessBillPay
            - PinlessBillPay
            - PinlessPOS
            - PinlessBillPayPinlessPOS
        cc:
          type: string
          enum:
            - Unknown
            - Business
            - Consumer
            - Corporate
            - Purchase
        cs:
          type: string
          enum:
            - Unknown
            - A2
            - C3
            - D4
            - D5
            - D6
            - D7
            - D8
            - D9
            - D10
            - D11
            - D12
            - D13
            - D14
            - D15
            - D16
            - D17
            - M18
            - M19
            - M20
            - M21
            - M22
            - M23
            - M24
            - M25
            - M26
            - M27
            - M28
            - M29
            - M30
            - M31
            - M32
            - M33
            - M34
            - M35
            - M36
            - M37
            - M38
            - M39
            - M40
            - M41
            - M42
            - M43
            - M44
            - M45
            - M46
            - M47
            - M48
            - M49
            - M50
            - M51
            - M52
            - M53
            - M54
            - M55
            - M56
            - M57
            - M58
            - M59
            - M60
            - M61
            - M62
            - M63
            - M64
            - M65
            - M66
            - M67
            - M68
            - M69
            - M70
            - M71
            - M72
            - M73
            - M74
            - M75
            - M76
            - M77
            - M78
            - M79
            - M80
            - M81
            - M82
            - M83
            - M84
            - M85
            - M86
            - M87
            - M88
            - M89
            - M90
            - M91
            - M92
            - M93
            - M94
            - M95
            - M96
            - M97
            - M98
            - M99
            - M100
            - M101
            - M102
            - M103
            - M104
            - M105
            - M106
            - M107
            - M108
            - M109
            - M110
            - M111
            - M112
            - M113
            - M114
            - M115
            - M116
            - M117
            - M118
            - M119
            - M120
            - M121
            - M122
            - M123
            - N124
            - P125
            - V126
            - V127
            - V128
            - V129
            - V130
            - V131
            - V132
            - V133
            - V134
            - V135
            - V136
            - V137
            - V138
            - V139
            - V140
            - V141
            - V142
            - V143
            - V144
            - V145
            - V146
            - V147
            - V148
            - V149
            - V150
            - V151
            - V152
            - V153
            - V154
            - V155
            - V156
            - V157
            - V158
            - V159
            - V160
            - V161
        currencyCode:
          type: string
    CurrencyReferenceInfo:
      type: object
      properties:
        currency:
          type: string
          enum:
            - Unknown
            - USD
            - AFN
            - DZD
            - ARS
            - AMD
            - AWG
            - AUD
            - AZN
            - BSD
            - BHD
            - THB
            - PAB
            - BBD
            - BYR
            - BZD
            - BMD
            - VEF
            - BOB
            - BRL
            - BND
            - BGN
            - BIF
            - CAD
            - CVE
            - KYD
            - XOF
            - XAF
            - XPF
            - CLP
            - COP
            - KMF
            - BAM
            - NIO
            - CRC
            - HRK
            - CUP
            - CZK
            - GMD
            - DKK
            - MKD
            - DJF
            - STD
            - DOP
            - VND
            - XCD
            - EGP
            - SVC
            - ETB
            - EUR
            - FKP
            - FJD
            - HUF
            - CDF
            - GHS
            - GIP
            - HTG
            - PYG
            - GNF
            - GWP
            - GYD
            - HKD
            - UAH
            - ISK
            - INR
            - IRR
            - IQD
            - JMD
            - JOD
            - KES
            - PGK
            - LAK
            - KWD
            - MWK
            - ZMK
            - AOA
            - MMK
            - GEL
            - LVL
            - LBP
            - ALL
            - HNL
            - SLL
            - LRD
            - LYD
            - SZL
            - LTL
            - LSL
            - MGA
            - MYR
            - MUR
            - MZN
            - MXN
            - MXV
            - MDL
            - MAD
            - BOV
            - NGN
            - ERN
            - NAD
            - NPR
            - ANG
            - ILS
            - RON
            - TWD
            - TRY
            - NZD
            - BTN
            - KPW
            - NOK
            - PEN
            - MRO
            - TOP
            - PKR
            - MOP
            - UYU
            - PHP
            - GBP
            - BWP
            - QAR
            - GTQ
            - ZAR
            - OMR
            - KHR
            - MVR
            - IDR
            - RUB
            - RWF
            - SHP
            - SAR
            - XDR
            - RSD
            - SCR
            - SGD
            - SBD
            - KGS
            - SOS
            - TJS
            - LKR
            - SDG
            - SRD
            - SEK
            - CHF
            - SYP
            - BDT
            - WST
            - TZS
            - KZT
            - TTD
            - MNT
            - TND
            - AED
            - UGX
            - COU
            - CLF
            - UYI
            - USN
            - USS
            - UZS
            - VUV
            - CHE
            - CHW
            - KRW
            - YER
            - JPY
            - CNY
            - PLN
            - XBA
            - XTS
            - XBB
            - XBD
            - XBC
            - XAU
            - XPD
            - XPT
            - XAG
            - XXX
            - XFU
            - TMT
            - ZWL
            - CUC
            - SSP
            - XUA
            - XSU
            - BYN
            - VES
            - ZMW
            - MRU
            - STN
            - SLE
            - BRC
            - ARX
        isoNumeric:
          type: string
        minorUnits:
          type: integer
          format: int32
        precision:
          type: integer
          format: int32
        name:
          type: string
        euroZone:
          type: boolean
    BinListResponse:
      type: object
      properties:
        updated:
          type: string
          format: date-time
        bins:
          uniqueItems: true
          type: array
          items:
            type: integer
            format: int32
    #-------------------------------------
    # ENUM Models
    #-------------------------------------
    RateType:
      description: Indicates the status of a token.
      type: string
      readOnly: true
      default: TD
      enum:
        - TD
        - TM
        - PD
        - PM
        - IC
  #-------------------------------------
  # Example
  #-------------------------------------
  examples:
    ExchangeRateRequest:
      value:
        bin: 123456
        source: AED
        rateType: AB
        sourceAmount: 1
        client: Dummy
        xref: '123412341234'

    ExchangeRateResponse:
      value:
        eligibility: 'Y'
        id: 159aef7f-0319-443d-af65-5aff7c901c9a
        margin: 4.99
        sourceAmount: 1
        targetAmount: 0.27
        rate:
          provider: Visa
          rate: 0.2676
          id: '44625021'
          start: '2024-02-09T00:00:00.000'
          end: '2025-03-10T23:59:59.000'
          source:
            alpha: AED
            numeric: 784
            minorUnits: 2
            symbol: AED
          target:
            alpha: EUR
            numeric: 978
            minorUnits: 2
            symbol: EUR

    ExchangeAllRateRequest:
      value:
        source: GBP
        rateType: TD
        client: DUMMY
        xref: '123451234512345'
    ExchangeAllRateRequestWithAmountRequest:
      value:
        source: USD
        sourceAmount: 101
        rateType: TD
        client: DUMMY
        xref: '123451234512'
    ExchangeAllRateRequestWithAmountAndTargetCurrencyRequest:
      value:
        source: USD
        target: MXN
        sourceAmount: 101
        rateType: TD
        client: DUMMY
        xref: '123451234512'
    ExchangeAllRateRequestWithTargetCurrencyRequest:
      value:
        source: USD
        target: MXN
        rateType: TD
        client: DUMMY
        xref: '123451234512'

    ExchangeAllRateResponse:
      value:
        id: 4a073415-a7cd-498a-b110-c1051e936cbe
        rates:
          - eligibility: 'Y'
            id: e8f307e2-4554-4808-bb65-66cff33b4656
            margin: 4.6
            rate:
              provider: Dummy
              rate: 17.8582534
              id: 0f8faf46-36da-4212-a942-bf80cacffd63
              start: '2024-02-20T00:00:00.000'
              end: '2025-02-21T21:55:13.000'
              source:
                alpha: USD
                numeric: 840
                minorUnits: 2
                symbol: USD
              target:
                alpha: MXN
                numeric: 484
                minorUnits: 2
                symbol: MXN
    ExchangeAllRateWithAmountResponse:
      value:
        id: 4a073415-a7cd-498a-b110-c1051e936cbe
        rates:
          - eligibility: 'Y'
            id: e8f307e2-4554-4808-bb65-66cff33b4656
            margin: 4.6
            sourceAmount: 101
            targetAmount: 1803.68
            rate:
              provider: Dummy
              rate: 17.8582534
              id: 0f8faf46-36da-4212-a942-bf80cacffd63
              start: '2024-02-20T00:00:00.000'
              end: '2025-02-21T21:55:13.000'
              source:
                alpha: USD
                numeric: 840
                minorUnits: 2
                symbol: USD
              target:
                alpha: MXN
                numeric: 484
                minorUnits: 2
                symbol: MXN
          - eligibility: 'Y'
            id: e8f307e2-4554-4808-bb65-66cff33b4656
            margin: 4.6
            sourceAmount: 101
            targetAmount: 1803.68
            rate:
              provider: Dummy
              rate: 17.8582534
              id: 0f8faf46-36da-4212-a942-bf80cacffd63
              start: '2024-02-20T00:00:00.000'
              end: '2025-02-21T21:55:13.000'
              source:
                alpha: USD
                numeric: 840
                minorUnits: 2
                symbol: USD
              target:
                alpha: MXN
                numeric: 484
                minorUnits: 2
                symbol: MXN
    ExchangeAllRateWithAmountAndTargetCurrencyResponse:
      value:
        id: 4a073415-a7cd-498a-b110-c1051e936cbe
        rates:
          - eligibility: 'Y'
            id: e8f307e2-4554-4808-bb65-66cff33b4656
            margin: 4.6
            sourceAmount: 101
            targetAmount: 1803.68
            rate:
              provider: Dummy
              rate: 17.8582534
              id: 0f8faf46-36da-4212-a942-bf80cacffd63
              start: '2024-02-20T00:00:00.000'
              end: '2025-02-21T21:55:13.000'
              source:
                alpha: USD
                numeric: 840
                minorUnits: 2
                symbol: USD
              target:
                alpha: MXN
                numeric: 484
                minorUnits: 2
                symbol: MXN
          - eligibility: 'Y'
            id: e8f307e2-4554-4808-bb65-66cff33b4656
            margin: 4.6
            sourceAmount: 101
            targetAmount: 1803.68
            rate:
              provider: Dummy
              rate: 17.8582534
              id: 0f8faf46-36da-4212-a942-bf80cacffd63
              start: '2024-02-20T00:00:00.000'
              end: '2025-02-21T21:55:13.000'
              source:
                alpha: USD
                numeric: 840
                minorUnits: 2
                symbol: USD
              target:
                alpha: MXN
                numeric: 484
                minorUnits: 2
                symbol: MXN
    ExchangeAllRateWithTargetCurrencyResponse:
      value:
        id: 560c89d4-bd5e-4649-9508-0a449ef56bea
        rates:
          - eligibility: 'Y'
            id: 234836ce-3351-4718-ab0f-4444b99c7181
            rate:
              provider: Dummy
              rate: 17.8582534
              id: 0f8faf46-36da-4212-a942-bf80cacffd63
              start: '2024-02-20T00:00:00.000'
              end: '2025-02-21T21:55:13.000'
              source:
                alpha: USD
                numeric: 840
                minorUnits: 2
                symbol: USD
              target:
                alpha: MXN
                numeric: 484
                minorUnits: 2
                symbol: MXN
          - eligibility: 'Y'
            id: 234836ce-3351-4718-ab0f-4444b99c7181
            margin: 4.6
            rate:
              provider: Dummy
              rate: 17.8582534
              id: 0f8faf46-36da-4212-a942-bf80cacffd63
              start: '2024-02-20T00:00:00.000'
              end: '2025-02-21T21:55:13.000'
              source:
                alpha: USD
                numeric: 840
                minorUnits: 2
                symbol: USD
              target:
                alpha: MXN
                numeric: 484
                minorUnits: 2
                symbol: MXN
    BinList:
      value:
        updated: '2024-02-20T22:44:06.568403'
        bins:
          - 48628450
          - 524301
          - 524289
          - 48628460
          - 524290
